name: Regression tests


runs:
  using: "composite"
  steps:
    - name: Install SDF-pipeline
      run: |
        python -m pipx install git+https://github.com/TUCAN-nest/SDF-pipeline.git
      shell: bash

    - name: Show gcc version
      run: |
        gcc --version
      shell: bash

    - name: Show ldd version
      run: |
        ldd --version
      shell: bash

    - name: Run regression tests
      run: python -m INCHI-1-TEST.run_regression_tests ci
      shell: bash

    - name: Upload regression test results
      if: '!cancelled()'
      uses: actions/upload-artifact@v3
      with:
        name: regression-test-results
        path: ./INCHI-1-TEST/data/ci/*_regression_test.log
