#include <gtest/gtest.h>

extern "C"
{
#include "../../../INCHI-1-SRC/INCHI_BASE/src/inchi_api.h"
#include "../../../INCHI-1-SRC/INCHI_BASE/src/mode.h"
}

/*
* (NaumanUllahKhan :: @nnuk)
* helper function to run the molfiles below as unit tests.
*/
static void ExpectedMolecularInorganicsInChI(const char* molblock,
                                           const char* expected_inchi,
                                           int expected_retcode)
{
    char options[] = "-MolecularInorganics";

    inchi_Output output;
    inchi_Output* poutput = &output;
    memset(poutput, 0, sizeof(*poutput));

    int ret = MakeINCHIFromMolfileText(molblock, options, poutput);

    EXPECT_EQ(ret, expected_retcode);
    ASSERT_NE(poutput->szInChI, nullptr);
    EXPECT_STREQ(poutput->szInChI, expected_inchi);

    FreeINCHI(poutput);
}

/* (NaumanUllahKhan :: @nnuk)
*  below are some tests with MI (MolecularInorganics) tags specific molfiles that go through the MI code pipeline.
*/
TEST(test_molecularInorganics, test_MI_1_VOF3)
{
    const char* molblock = R"(
  ACCLDraw12222500412D

  5  4  0  0  0  0  0  0  0  0999 V2000
    6.6078   -5.5530    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
    7.6307   -4.9625    0.0000 V   0  0  0  0  0  0  0  0  0  0  0  0
    7.6307   -3.7814    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    8.4658   -5.7976    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
    8.7715   -5.2681    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
  2  4  1  0  0  0  0
  2  5  1  0  0  0  0
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/F3OV/c1-5(2,3)4", 0);
}

TEST(test_molecularInorganics, test_MI_2_FeF4)
{
    const char* molblock = R"(
  ACCLDraw11252412092D

  5  4  0  0  0  0  0  0  0  0999 V2000
   19.0241  -15.5577    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
   17.0325  -15.0985    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
   17.9929  -14.5328    0.0000 Fe  0  0  0  0  0  0  0  0  0  0  0  0
   19.3285  -14.6295    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
   17.9928  -13.3513    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
  3  1  1  0  0  0  0
  3  2  1  0  0  0  0
  3  4  1  0  0  0  0
  3  5  1  0  0  0  0
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/F4Fe/c1-5(2,3)4", 0);
}

TEST(test_molecularInorganics, test_MI_3_FeF3)
{
    const char* molblock = R"(
  ACCLDraw11252412082D

  4  3  0  0  0  0  0  0  0  0999 V2000
   17.9929  -15.7140    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
   16.9700  -13.9423    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
   17.9929  -14.5328    0.0000 Fe  0  0  0  0  0  0  0  0  0  0  0  0
   19.0160  -13.9420    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
  3  1  1  0  0  0  0
  3  2  1  0  0  0  0
  3  4  1  0  0  0  0
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/3FH.Fe/h3*1H;/q;;;+3/p-3", 1);
}

TEST(test_molecularInorganics, test_MI_4_FeCl3)
{
    const char* molblock = R"(
  ACCLDraw11212415402D

  4  3  0  0  0  0  0  0  0  0999 V2000
    5.3438   -5.7436    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    4.3209   -3.9719    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    6.3666   -3.9719    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    5.3438   -4.5625    0.0000 Fe  0  0  0  0  0  0  0  0  0  0  0  0
  4  1  1  0  0  0  0
  4  2  1  0  0  0  0
  4  3  1  0  0  0  0
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/Cl3Fe/c1-4(2)3", 0);
}

TEST(test_molecularInorganics, test_MI_5_hydrido_dimethyl_iron)
{
    const char* molblock = R"(hydrido(dimethyl)iron
  ACCLDraw11182517382D

  4  3  0  0  0  0  0  0  0  0999 V2000
    6.0938   -6.6250    0.0000 Fe  0  0  0  0  0  0  0  0  0  0  0  0
    7.1166   -6.0344    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    5.0709   -6.0344    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.0938   -7.8061    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  3  1  0  0  0  0
  1  4  1  0  0  0  0
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/C2H7Fe/c1-3(2)4/h1-2H3", 0);
}

TEST(test_molecularInorganics, test_MI_6_Pt_haptic)
{
    const char* molblock = R"(
  ACCLDraw04282514232D

  0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 7 5 0 0 0
M  V30 BEGIN ATOM
M  V30 1 Cl 7.4847 -4.7161 0 0
M  V30 2 Cl 8.8623 -5.8977 0 0
M  V30 3 Cl 7.5377 -7.0884 0 0
M  V30 4 Pt 7.5222 -5.8893 0 0 CHG=-1
M  V30 5 * 5.9997 -5.9174 0 0
M  V30 6 C 5.9061 -5.327 0 0
M  V30 7 C 5.9061 -6.5078 0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 4 1
M  V30 2 1 4 2
M  V30 3 1 4 3
M  V30 4 9 4 5 ENDPTS=(2 6 7) ATTACH=ALL
M  V30 5 2 7 6
M  V30 END BOND
M  V30 END CTAB
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/C2H4Cl3Pt/c3-6(4,5)1-2-6/h1-2H2/q-1", 1);
}

TEST(test_molecularInorganics, test_MI_GHI_218)
{
    const char* molblock = R"(stereochemistry.ds/mol_stereochemistry.ds_145.mol
Generated by WebMolKit

  0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 45 52 0 0 1
M  V30 BEGIN ATOM
M  V30 1 Ti 7.3506 0.0000 0.0000 0
M  V30 2 O 6.1371 1.3858 0.0000 0
M  V30 3 O 8.5641 -1.3858 0.0000 0
M  V30 4 O 8.5641 1.3858 0.0000 0
M  V30 5 O 6.1371 -1.3858 0.0000 0
M  V30 6 O 8.1318 5.5124 0.0000 0
M  V30 7 O 6.5694 -5.5124 0.0000 0
M  V30 8 O 3.4466 2.8024 0.0000 0
M  V30 9 O 11.2546 -2.8024 0.0000 0
M  V30 10 O 3.3839 8.2243 0.0000 0
M  V30 11 O 11.3173 -8.2243 0.0000 0
M  V30 12 O 10.3725 1.5381 0.0000 0
M  V30 13 O 4.3287 -1.5381 0.0000 0
M  V30 14 O 14.9023 4.0839 0.0000 0
M  V30 15 O -0.2011 -4.0839 0.0000 0
M  V30 16 C 6.6006 2.8123 0.0000 0
M  V30 17 C 8.1006 -2.8123 0.0000 0
M  V30 18 C 8.1006 2.8123 0.0000 0
M  V30 19 C 6.6006 -2.8123 0.0000 0
M  V30 20 C 5.7985 4.1534 0.0000 0
M  V30 21 C 8.9025 -4.1534 0.0000 0
M  V30 22 C 8.9025 4.1534 0.0000 0
M  V30 23 C 5.7985 -4.1534 0.0000 0
M  V30 24 C 6.5694 5.5124 0.0000 0
M  V30 25 C 8.1318 -5.5124 0.0000 0
M  V30 26 C 10.4025 4.1360 0.0000 0
M  V30 27 C 4.2987 -4.1360 0.0000 0
M  V30 28 C 4.1715 4.1157 0.0000 0
M  V30 29 C 10.5297 -4.1157 0.0000 0
M  V30 30 C 5.7664 6.9281 0.0000 0
M  V30 31 C 8.9346 -6.9281 0.0000 0
M  V30 32 C 3.3361 5.5124 0.0000 0
M  V30 33 C 11.3651 -5.5124 0.0000 0
M  V30 34 C 4.1389 6.9281 0.0000 0
M  V30 35 C 10.5621 -6.9281 0.0000 0
M  V30 36 C 11.1374 2.8284 0.0000 0
M  V30 37 C 3.5636 -2.8284 0.0000 0
M  V30 38 C 11.1676 5.4263 0.0000 0
M  V30 39 C 3.5336 -5.4263 0.0000 0
M  V30 40 C 12.6374 2.8110 0.0000 0
M  V30 41 C 2.0638 -2.8110 0.0000 0
M  V30 42 C 12.6674 5.4089 0.0000 0
M  V30 43 C 2.0338 -5.4089 0.0000 0
M  V30 44 C 13.4023 4.1013 0.0000 0
M  V30 45 C 1.2988 -4.1013 0.0000 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 2 2 16
M  V30 2 2 3 17
M  V30 3 1 4 18
M  V30 4 1 5 19
M  V30 5 1 6 22
M  V30 6 1 6 24
M  V30 7 1 7 23
M  V30 8 1 7 25
M  V30 9 1 8 28
M  V30 10 1 9 29
M  V30 11 1 10 34
M  V30 12 1 11 35
M  V30 13 1 12 36
M  V30 14 1 13 37
M  V30 15 1 14 44
M  V30 16 1 15 45
M  V30 17 1 16 18
M  V30 18 1 16 20
M  V30 19 1 17 19
M  V30 20 1 17 21
M  V30 21 2 18 22
M  V30 22 2 19 23
M  V30 23 1 20 24
M  V30 24 2 20 28
M  V30 25 1 21 25
M  V30 26 2 21 29
M  V30 27 1 22 26
M  V30 28 1 23 27
M  V30 29 2 24 30
M  V30 30 2 25 31
M  V30 31 2 26 36
M  V30 32 1 26 38
M  V30 33 2 27 37
M  V30 34 1 27 39
M  V30 35 1 28 32
M  V30 36 1 29 33
M  V30 37 1 30 34
M  V30 38 1 31 35
M  V30 39 2 32 34
M  V30 40 2 33 35
M  V30 41 1 36 40
M  V30 42 1 37 41
M  V30 43 2 38 42
M  V30 44 2 39 43
M  V30 45 2 40 44
M  V30 46 2 41 45
M  V30 47 1 42 44
M  V30 48 1 43 45
M  V30 49 1 1 5
M  V30 50 1 1 4 CFG=3
M  V30 51 9 1 2 CFG=1 DISP=COORD
M  V30 52 9 1 3 DISP=COORD
M  V30 END BOND
M  V30 END CTAB
M  END)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/C30H18O14Ti/c31-11-1-3-15(17(35)5-11)25-29-27(23-19(37)7-13(33)9-21(23)39-25)41-45(43-29)42-28-24-20(38)8-14(34)10-22(24)40-26(30(28)44-45)16-4-2-12(32)6-18(16)36/h1-10,31-38H", 1);
}

TEST(test_molecularInorganics, test_MI_Na_H2O_CoordBond)
{
    const char* molblock = R"(
  ACCLDraw06092610472D

  0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 2 1 0 0 0
M  V30 BEGIN ATOM
M  V30 1 O 3.3082 -5.8926 0 0 VAL=1
M  V30 2 Na 2.2853 -6.4832 0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 9 1 2
M  V30 END BOND
M  V30 END CTAB
M  END
)";

     ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/Na.H2O/h;1H2/q+1;/p-1", 1);
}

TEST(test_molecularInorganics, test_MI_Na_H2O_CoordBond_Charged)
{
    const char* molblock = R"(
  ACCLDraw06092610502D

  0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 2 1 0 0 0
M  V30 BEGIN ATOM
M  V30 1 Na 1.9415 -11.2332 0 0 CHG=1
M  V30 2 O 2.9644 -10.6426 0 0 CHG=-1
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 9 2 1
M  V30 END BOND
M  V30 END CTAB
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/Na.H2O/h;1H2/q+1;/p-1", 1);
}

TEST(test_molecularInorganics, test_MI_Na_Methoxide_Charged)
{
    const char molblock[] = R"(
  ACCLDraw06092600112D

  0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 3 2 0 0 0
M  V30 BEGIN ATOM
M  V30 1 Na 3.2848 -9.6749 0 0 CHG=1
M  V30 2 O 4.3077 -9.0843 0 0 CHG=-1
M  V30 3 C 5.3309 -9.675 0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 9 2 1
M  V30 2 1 2 3
M  V30 END BOND
M  V30 END CTAB
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/CH3O.Na/c1-2;/h1H3;/q-1;+1", 1);
}

TEST(test_molecularInorganics, test_MI_Na_Methoxide_Valence1)
{
    const char molblock[] = R"(
  ACCLDraw06092600112D

  0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 3 2 0 0 0
M  V30 BEGIN ATOM
M  V30 1 Na 3.5661 -6.1124 0 0
M  V30 2 O 4.589 -5.5218 0 0 VAL=1
M  V30 3 C 5.6121 -6.1125 0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 9 2 1
M  V30 2 1 2 3
M  V30 END BOND
M  V30 END CTAB
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/CH3O.Na/c1-2;/h1H3;/q-1;+1", 1);
}


TEST(test_molecularInorganics, test_MI_Na_H2O_V2000_Charged)
{
    const char molblock[] = R"(
  ACCLDraw06092611092D

  2  1  0  0  0  0  0  0  0  0999 V2000
   11.6670  -10.9290    0.0000 Na  0  3  0  0  0  0  0  0  0  0  0  0
   12.6899  -10.3384    0.0000 O   0  5  0  0  0  2  0  0  0  0  0  0
  2  1  1  0  0  0  0
M  CHG  2   1   1   2  -1
M  END
)";

     ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/Na.H2O/h;1H2/q+1;/p-1", 1);
}

/* (@fbaensch) Charge accounting for multiply-charged coordinative (type 9)
 * metal-ligand bonds: the charge cancellation happens only at the bond-
 * replacement site (type 9 -> type 1); disconnection must not alter charges.
 * Each coordinative bond therefore sheds one charge unit per endpoint, and
 * the resulting ions disconnect with the remaining formal charges intact. */

TEST(test_molecularInorganics, test_MI_NaOH_charged_disconnected)
{
    const char* molblock = R"(
  ACCLDraw06152616342D

  2  0  0  0  0  0  0  0  0  0999 V2000
   16.3750   -5.1250    0.0000 Na  0  3  0  0  0  0  0  0  0  0  0  0
   17.5313   -3.7500    0.0000 O   0  5  0  0  0  0  0  0  0  0  0  0
M  CHG  2   1   1   2  -1
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/Na.H2O/h;1H2/q+1;/p-1", 1);
}

TEST(test_molecularInorganics, test_MI_NaOH_charged_coordinative)
{
    const char* molblock = R"(
  -INDIGO-06172612032D

  0  0  0  0  0  0  0  0  0  0  0 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 2 1 0 0 0
M  V30 BEGIN ATOM
M  V30 1 Na 4.675 -6.475 0.0 0 CHG=2
M  V30 2 O 6.25711 -4.84289 0.0 0 CHG=-2 VAL=2
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 9 2 1
M  V30 END BOND
M  V30 END CTAB
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/Na.H2O/h;1H2/q+2;-2", 1);
}

TEST(test_molecularInorganics, test_MI_NaO_charged_coordinative)
{
    const char* molblock = R"(
  -INDIGO-06172612042D

  0  0  0  0  0  0  0  0  0  0  0 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 2 1 0 0 0
M  V30 BEGIN ATOM
M  V30 1 Na 4.675 -6.475 0.0 0 CHG=2
M  V30 2 O 6.25711 -4.84289 0.0 0 CHG=-2
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 9 2 1
M  V30 END BOND
M  V30 END CTAB
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/Na.O/q+2;-2", 1);
}

TEST(test_molecularInorganics, test_MI_NaONa_charged_coordinative)
{
    const char* molblock = R"(
  -INDIGO-06172612062D

  0  0  0  0  0  0  0  0  0  0  0 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 3 2 0 0 0
M  V30 BEGIN ATOM
M  V30 1 Na 4.675 -6.475 0.0 0 CHG=1
M  V30 2 O 6.25711 -4.84289 0.0 0 CHG=-2
M  V30 3 Na 7.48921 -6.225 0.0 0 CHG=1
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 9 2 1
M  V30 2 9 2 3
M  V30 END BOND
M  V30 END CTAB
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/2Na.O/q2*+1;-2", 1);
}

TEST(test_molecularInorganics, test_MI_MgO_charged_coordinative)
{
    const char* molblock = R"(
  -INDIGO-06172612352D

  0  0  0  0  0  0  0  0  0  0  0 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 2 1 0 0 0
M  V30 BEGIN ATOM
M  V30 1 Mg 6.48135 -5.51875 0.0 0 CHG=2
M  V30 2 O 8.63135 -5.49375 0.0 0 CHG=-2
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 9 2 1
M  V30 END BOND
M  V30 END CTAB
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/Mg.O/q+2;-2", 1);
}


TEST(test_molecularInorganics, test_MI_Issue244_TitaniumComplex_1)
{
    const char* molblock = R"(
  ACCLDraw07162620392D

  9  9  0  0  0  0  0  0  0  0999 V2000
    8.5060   -5.7490    0.0000 Ti  0  0  0  0  0  0  0  0  0  0  0  0
    7.5504   -5.0548    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.9154   -3.9315    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.0965   -3.9315    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.4615   -5.0548    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.2963   -6.6268    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.7156   -6.6268    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    6.5745   -6.3210    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.4519   -6.3811    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
  3  4  1  0  0  0  0
  4  5  1  0  0  0  0
  5  1  1  0  0  0  0
  1  6  1  0  0  0  0
  1  7  1  0  0  0  0
  7  8  1  0  0  0  0
  6  9  1  0  0  0  0
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/C4H10O4Ti/c1-5-9(6-2)7-3-4-8-9/h3-4H2,1-2H3", 0);
}


TEST(test_molecularInorganics, test_MI_Issue244_CalciumOxalate)
{
    const char* molblock = R"(
  ACCLDraw07162620412D

  7  7  0  0  0  0  0  0  0  0999 V2000
    6.5036   -5.6703    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    6.8686   -4.5470    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.1744   -3.5914    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    8.0497   -4.5470    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.7439   -3.5915    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    8.4147   -5.6703    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.4592   -6.3645    0.0000 Ca  0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
  2  4  1  0  0  0  0
  4  5  2  0  0  0  0
  4  6  1  0  0  0  0
  1  7  1  0  0  0  0
  6  7  1  0  0  0  0
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/C2H2O4.Ca/c3-1(4)2(5)6;/h(H,3,4)(H,5,6);/q;+2/p-2", 1);
}


TEST(test_molecularInorganics, test_MI_Issue244_CalciumSulfate)
{
    const char* molblock = R"(
  ACCLDraw07162620432D

  6  6  0  0  0  0  0  0  0  0999 V2000
   11.5075   -6.5032    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   12.6886   -6.5032    0.0000 S   0  0  3  0  0  0  0  0  0  0  0  0
   12.6886   -5.3221    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   12.6886   -7.6843    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.8697   -6.5032    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   11.5075   -7.6843    0.0000 Ca  0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
  2  4  1  0  0  0  0
  2  5  2  0  0  0  0
  1  6  1  0  0  0  0
  4  6  1  0  0  0  0
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/Ca.H2O4S/c;1-5(2,3)4/h;(H2,1,2,3,4)/q+2;/p-2", 1);
}


TEST(test_molecularInorganics, test_MI_Issue244_CalciumCitrate)
{
    const char* molblock = R"(
  ACCLDraw07162620472D

 23 24  0  0  0  0  0  0  0  0999 V2000
    8.3521   -6.5060    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.3750   -5.9155    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.3750   -4.7344    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   10.3978   -6.5060    0.0000 C   0  0  3  0  0  0  0  0  0  0  0  0
   11.4207   -5.9155    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.3978   -7.6871    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.4207   -8.2777    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.3750   -8.2777    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   11.4207   -4.7344    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   12.4436   -6.5060    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.4664   -5.9155    0.0000 Ca  0  0  0  0  0  0  0  0  0  0  0  0
   18.5808   -6.5060    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   17.5579   -4.7344    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   15.5122   -8.2777    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   17.5579   -8.2777    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   16.5350   -7.6871    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.5579   -5.9155    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   16.5350   -6.5060    0.0000 C   0  0  3  0  0  0  0  0  0  0  0  0
   15.5122   -4.7344    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   15.5122   -5.9155    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   14.4893   -6.5060    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    8.3521   -7.6875    0.0000 Ca  0  0  0  0  0  0  0  0  0  0  0  0
   18.5811   -7.6869    0.0000 Ca  0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
  2  4  1  0  0  0  0
  4  5  1  0  0  0  0
  4  6  1  0  0  0  0
  6  7  2  0  0  0  0
  6  8  1  0  0  0  0
  5  9  2  0  0  0  0
  5 10  1  0  0  0  0
 10 11  1  0  0  0  0
 17 12  1  0  0  0  0
 17 13  2  0  0  0  0
 16 14  2  0  0  0  0
 16 15  1  0  0  0  0
 18 16  1  0  0  0  0
 18 17  1  0  0  0  0
 20 18  1  0  0  0  0
 20 19  2  0  0  0  0
 21 20  1  0  0  0  0
 21 11  1  0  0  0  0
  1 22  1  0  0  0  0
  8 22  1  0  0  0  0
 15 23  1  0  0  0  0
 12 23  1  0  0  0  0
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/2C4H4O6.3Ca/c2*5-2(6)1(3(7)8)4(9)10;;;/h2*1H,(H,5,6)(H,7,8)(H,9,10);;;/q;;3*+2/p-6", 1);
}


TEST(test_molecularInorganics, test_MI_Issue245_DisodiumSulfate)
{
    const char* molblock = R"(
  ACCLDraw07162621292D

  7  6  0  0  0  0  0  0  0  0999 V2000
   14.6969   -5.9346    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   15.8780   -7.1157    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   14.6969   -7.1157    0.0000 S   0  0  3  0  0  0  0  0  0  0  0  0
   14.6969   -8.2968    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.5158   -7.1157    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   12.9250   -8.1388    0.0000 Na  0  0  0  0  0  0  0  0  0  0  0  0
   15.7200   -8.8875    0.0000 Na  0  0  0  0  0  0  0  0  0  0  0  0
  3  1  2  0  0  0  0
  3  2  2  0  0  0  0
  5  3  1  0  0  0  0
  3  4  1  0  0  0  0
  5  6  1  0  0  0  0
  4  7  1  0  0  0  0
M  END
)";

    ExpectedMolecularInorganicsInChI(molblock, "InChI=1B/2Na.H2O4S/c;;1-5(2,3)4/h;;(H2,1,2,3,4)/q2*+1;/p-2", 1);
}
