set(INCHI_VERSION_HEADER "${CMAKE_CURRENT_LIST_DIR}/../INCHI-1-SRC/INCHI_BASE/src/inchi_version.h")

file(STRINGS "${INCHI_VERSION_HEADER}" INCHI_VERSION_FULL_DEFINITION
    REGEX "^#define INCHI_SOFTWARE_VERSION \"[0-9][0-9][0-9][0-9]\\.[0-9]+(-[a-z0-9]+(_[a-z0-9]+)*)?\"$")
file(STRINGS "${INCHI_VERSION_HEADER}" INCHI_SOVERSION_DEFINITION
    REGEX "^#define INCHI_SOVERSION [0-9][0-9]*$")

if(NOT INCHI_VERSION_FULL_DEFINITION MATCHES "^#define INCHI_SOFTWARE_VERSION \"([^\"]+)\"$")
    message(FATAL_ERROR "Unable to read INCHI_SOFTWARE_VERSION from ${INCHI_VERSION_HEADER}")
endif()
set(INCHI_VERSION_FULL "${CMAKE_MATCH_1}")

if(NOT INCHI_SOVERSION_DEFINITION MATCHES "^#define INCHI_SOVERSION ([0-9][0-9]*)$")
    message(FATAL_ERROR "Unable to read INCHI_SOVERSION from ${INCHI_VERSION_HEADER}")
endif()
set(INCHI_SOVERSION "${CMAKE_MATCH_1}")

if(NOT INCHI_VERSION_FULL MATCHES "^[0-9][0-9][0-9][0-9]\\.(0|[1-9][0-9]*)(-[a-z0-9]+(_[a-z0-9]+)*)?$")
    message(FATAL_ERROR
        "INCHI_VERSION_FULL must match YYYY.MINOR[-lowercase_modifier], got '${INCHI_VERSION_FULL}'"
    )
endif()

string(REGEX MATCH "^([0-9][0-9][0-9][0-9])\\.([0-9]+)" INCHI_VERSION_MATCH "${INCHI_VERSION_FULL}")
set(INCHI_VERSION_YEAR "${CMAKE_MATCH_1}")
set(INCHI_VERSION_MINOR "${CMAKE_MATCH_2}")

file(STRINGS "${INCHI_VERSION_HEADER}" INCHI_VERSION_YEAR_DEFINITION
    REGEX "^#define INCHI_VERSION_YEAR [0-9][0-9][0-9][0-9]$")
file(STRINGS "${INCHI_VERSION_HEADER}" INCHI_VERSION_MINOR_DEFINITION
    REGEX "^#define INCHI_VERSION_MINOR [0-9][0-9]*$")

if(NOT INCHI_VERSION_YEAR_DEFINITION STREQUAL "#define INCHI_VERSION_YEAR ${INCHI_VERSION_YEAR}" OR
   NOT INCHI_VERSION_MINOR_DEFINITION STREQUAL "#define INCHI_VERSION_MINOR ${INCHI_VERSION_MINOR}")
    message(FATAL_ERROR
        "INCHI_VERSION_YEAR and INCHI_VERSION_MINOR in ${INCHI_VERSION_HEADER} must match INCHI_SOFTWARE_VERSION")
endif()
