[project]
name = "inchi_tests"
version = "1.0.0"
requires-python = ">=3.11,<3.13"
dependencies = ["pydantic == 2.11.5", "pytest == 9.0.3"]

[tool.setuptools.packages.find]
where = ["src", "tests/test_library"]
include = ["sdf_pipeline", "inchi_tests"]
namespaces = false

[tool.pytest.ini_options]
testpaths = ["tests/test_executable", "tests/test_meta"]
addopts = "-v"
